name: anexpress
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.2+2

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  app_settings: ^5.0.0
  bloc: ^8.1.2
  cached_network_image: ^3.2.1
  carousel_slider: ^4.2.1
  collection: ^1.17.1
  connectivity_plus: ^4.0.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^5.3.2
  dotted_border: 2.0.0+3
  encrypt: ^5.0.1
  equatable: ^2.0.5
  firebase_core: ^2.15.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.10.3
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  get_it: ^7.6.0
  google_fonts: ^4.0.4
  http: ^1.1.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  loader_overlay: ^2.3.0
  logger: ^1.1.0
  onesignal_flutter: ^3.5.1
  pin_code_fields: ^8.0.1
  proste_bezier_curve: ^2.0.2
  qr_flutter: ^4.1.0
  sentry_flutter: ^7.9.0
  shared_preferences: ^2.2.0
  simple_animations: ^5.0.2
  smooth_page_indicator: ^1.1.0
  stacked_services: ^1.3.0
  upgrader: ^8.0.0
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2

dev_dependencies:
  bloc_test: ^9.1.3
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# dart run change_app_package_name:main com.anexpress.app
flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/App-Icon-an-express.png" #"assets/images/icon-710x599-android.png"
  image_path_ios: "assets/images/App-Icon-an-express.png" #"assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/App-Icon-an-express.png" #"assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/App-Icon-an-express.png" #"assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#2E308D"

# flutter pub run flutter_launcher_icons
flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
